language: python
python:
  - "3.7"
# command to install dependencies
install: 
- python3 -m pip install poetry
- poetry debug:info
- poetry install
script: 
- poetry run flake8
- poetry run pytest
after_success:
- coverage run -m pytest tests 
- pip install codecov
- codecov
- bash <(curl -s https://codecov.io/bash)
